# Generated by Django 4.1 on 2022-08-29 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msgr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
